version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=recuperacao
      - POSTGRES_DB=minhasfinancas
    ports:
      - 8000:5432

volumes:
  pg-data: